Import Kodi 16.1 from kszaq's LibreELEC Amlogic branch

diff --git a/scripts/extract b/scripts/extract
--- a/scripts/extract
+++ b/scripts/extract
@@ -2,7 +2,7 @@
 
 ################################################################################
 #      This file is part of OpenELEC - http://www.openelec.tv
-#      Copyright (C) 2009-2014 Stephan Raue (stephan@openelec.tv)
+#      Copyright (C) 2009-2016 Stephan Raue (stephan@openelec.tv)
 #
 #  OpenELEC is free software: you can redistribute it and/or modify
 #  it under the terms of the GNU General Public License as published by
@@ -25,21 +25,18 @@ if [ -z "$3" ]; then
   exit 1
 fi
 
-[ -z "$PKG_URL" ] && exit 1
+[ -z "$PKG_URL" -o -z "$PKG_SOURCE_NAME" ] && exit 1
 [ ! -d "$SOURCES/$1" -o ! -d "$3" ] && exit 1
 
-for i in $PKG_URL; do
-  FILE="`basename $i`"
-
-  case $FILE in
+case $PKG_SOURCE_NAME in
   $2)
-    f="$SOURCES/$1/$FILE"
+    f="$SOURCES/$1/$PKG_SOURCE_NAME"
     if [ ! -f $f ]; then
-      echo "error: File $FILE doesn't exists in package $1 sources directory"
+      echo "error: File $PKG_SOURCE_NAME doesn't exists in package $1 sources directory"
       echo "have you called scripts/extract before scripts/get ?"
       exit 1
     fi
-    case $FILE in
+    case $PKG_SOURCE_NAME in
       *.tar)
         tar xf $f -C $3
         ;;
@@ -57,8 +54,7 @@ for i in $PKG_URL; do
         7z x -o$3/$1 $f
         ;;
       *.zip)
-        mkdir -p $3/$1
-        unzip -q $f -d $3/$1
+        unzip -q $f -d $3
         ;;
       *.diff | *.patch)
         cat $f | patch -d $3 -p1
@@ -74,5 +70,4 @@ for i in $PKG_URL; do
         ;;
     esac
     ;;
-  esac
-done
+esac
